fun main() {
    var pilha: Empilhavel  = PilhaDinamica(7)
    pilha.empilhar("Vermelho")
    pilha.empilhar("Amarelo")
    println("Topo: ${pilha.espiar()}")
    pilha.empilhar("Branco")
    pilha.empilhar("Rosa")
    pilha.empilhar("Laranja")
    pilha.empilhar("Roxo")
    println("Topo: ${pilha.espiar()}")
    val conteudo = pilha.desempilhar()
    pilha.desempilhar()
    pilha.empilhar("Turquesa")
    pilha.empilhar("Cobre")
    pilha.empilhar("Salmão")
    pilha.empilhar(pilha.desempilhar())
    pilha.empilhar(conteudo)
    println("Pilha=${pilha.imprimir()}")
}