fun main(args: Array<String>) {
    var pilha: EmpilhavelDupla = PilhaDupla(14)
    pilha.empilhar1("Manga")
    pilha.empilhar1("Uva")
    println("Topo:${pilha.topo1()}")
    pilha.empilhar2("Azul")
    pilha.empilhar2("Rosa")
    pilha.empilhar1("Morango")
    pilha.empilhar1("Damasco")
    println("Topo:${pilha.topo2()}")
    pilha.empilhar2("Dourado")
    pilha.empilhar1("Ameixa")
    pilha.empilhar2("Verde")
    pilha.empilhar2("Preto")	
    pilha.empilhar1("Maçã")	
    println("Topo:${pilha.topo1()}")
    val conteudo1 = pilha.desempilhar1()
    pilha.desempilhar1()
    pilha.empilhar2("Vermelho")	
    pilha.empilhar1("Graviola")
    pilha.empilhar1("Banana")
    println("Topo:${pilha.topo2()}")	
    val conteudo2 = pilha.desempilhar2()	
    pilha.empilhar1("Goiaba")   
    pilha.empilhar1(pilha.desempilhar1())
    pilha.desempilhar2();
    pilha.empilhar2("Amarelo")	
    pilha.empilhar1(conteudo1)
    pilha.empilhar2(pilha.desempilhar2())
    pilha.empilhar2(conteudo2)
    println("Pilha1=${pilha.imprimir1()}")
    println("Pilha2=${pilha.imprimir2()}")			
}